# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SOAP-Lite-Simple
version:      1.9
version_from: 
installdirs:  site
requires:
    SOAP::XML::Client:             1.9

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
